/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import javax.swing.JOptionPane;
import logicadenegocios.xmlDocument;
import logicadenegocios.Pais;

/**
 *
 * @author pc
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    private Pais country = null;
    private xmlDocument doc = new xmlDocument();
    public Ventana1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelName = new javax.swing.JLabel();
        LabelArea = new javax.swing.JLabel();
        LabelPoblacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelLimite = new javax.swing.JLabel();
        LabelProvincia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        NombreP = new javax.swing.JTextField();
        AreaP = new javax.swing.JTextField();
        PoblacionP = new javax.swing.JTextField();
        IdiomaP = new javax.swing.JTextField();
        LimiteText = new javax.swing.JTextField();
        ProvinciaText = new javax.swing.JTextField();
        AgregarPais = new javax.swing.JButton();
        AgregarLimite = new javax.swing.JButton();
        agregarProvincia = new javax.swing.JButton();
        AgregarPaises = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelName.setText("Nombre del país: ");
        getContentPane().add(LabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        LabelArea.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelArea.setText("Área del país: ");
        getContentPane().add(LabelArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        LabelPoblacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelPoblacion.setText("Cantidad de poblacion: ");
        getContentPane().add(LabelPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Idioma del país: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        LabelLimite.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelLimite.setText("Ingrese Limite:");
        getContentPane().add(LabelLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        LabelProvincia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelProvincia.setText("Ingres Provincia:");
        getContentPane().add(LabelProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setText("Ejemplo de documento XML");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 427, -1, 10));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Crear el Docuemento XML");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(0, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Nota: \n\tUna vez que agregas un país actual \npuedes agregar limites y provincias. Sino \nagregas ningún limite o provincia estará \nvacío en el documento xml.\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 350, 140));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("<?xml version=\"0.1\" encoding=\"UFT-8\" standalone=\"no\"?>\n<Paises>\n\t<País>\n\t\t<Nombre>Costa Rica</Nombre>\n\t\t<Área>51<<Área>\n\t\t<Población></Población>\n\t\t<Provincias>\n\t\t\t<Provincia>Limón</Provincia>\n\t\t</Provincias>\n\t\t<Limites>\n\t\t\t<Limite>Panamá</Limite>\n\t\t</Limites>\n\t</País>\n</Paises>");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 440, 220));

        NombreP.setBackground(new java.awt.Color(102, 255, 255));
        NombreP.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        NombreP.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(NombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, -1));

        AreaP.setBackground(new java.awt.Color(102, 255, 255));
        AreaP.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        AreaP.setForeground(new java.awt.Color(0, 51, 255));
        AreaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaPActionPerformed(evt);
            }
        });
        getContentPane().add(AreaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        PoblacionP.setBackground(new java.awt.Color(102, 255, 255));
        PoblacionP.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        PoblacionP.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(PoblacionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 170, -1));

        IdiomaP.setBackground(new java.awt.Color(102, 255, 255));
        IdiomaP.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        IdiomaP.setForeground(new java.awt.Color(0, 51, 255));
        IdiomaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaPActionPerformed(evt);
            }
        });
        getContentPane().add(IdiomaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));

        LimiteText.setBackground(new java.awt.Color(102, 255, 255));
        LimiteText.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        LimiteText.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(LimiteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 170, -1));

        ProvinciaText.setBackground(new java.awt.Color(102, 255, 255));
        ProvinciaText.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        ProvinciaText.setForeground(new java.awt.Color(0, 51, 255));
        getContentPane().add(ProvinciaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 160, -1));

        AgregarPais.setBackground(new java.awt.Color(0, 51, 255));
        AgregarPais.setForeground(new java.awt.Color(255, 255, 255));
        AgregarPais.setText("Agregar país actual");
        AgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPaisActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        AgregarLimite.setBackground(new java.awt.Color(0, 0, 255));
        AgregarLimite.setForeground(new java.awt.Color(255, 255, 255));
        AgregarLimite.setText("Agregar Provincia");
        AgregarLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarLimiteActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        agregarProvincia.setBackground(new java.awt.Color(0, 51, 255));
        agregarProvincia.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        agregarProvincia.setForeground(new java.awt.Color(255, 255, 255));
        agregarProvincia.setText("Agregar Provincia");
        agregarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProvinciaActionPerformed(evt);
            }
        });
        getContentPane().add(agregarProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));

        AgregarPaises.setBackground(new java.awt.Color(51, 51, 255));
        AgregarPaises.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        AgregarPaises.setForeground(new java.awt.Color(255, 255, 255));
        AgregarPaises.setText("Agregar país a la estructura");
        AgregarPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPaisesActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarPaises, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 0, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 0));
        jButton5.setText("Guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 392, 1010, 310));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 550, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaPActionPerformed

    private void IdiomaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdiomaPActionPerformed

    private void AgregarLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarLimiteActionPerformed
        // TODO add your handling code here:
        if(country != null){
            String limite = LimiteText.getText();
            country.agregarLimite(limite);
            LimiteText.setText("");
        }else{
            ProvinciaText.setText("");
            LimiteText.setText("");
            JOptionPane.showMessageDialog(null, "Error!\n¡No hay agregado un país!");
        }
    }//GEN-LAST:event_AgregarLimiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPaisActionPerformed
        // TODO add your handling code here:
        try{
            String nombre = NombreP.getText();
            String area = AreaP.getText();
            String people = PoblacionP.getText();
            String lenguage = IdiomaP.getText();
            if(!nombre.equals("") & !area.equals("") & !people.equals("") & !lenguage.equals("")){
                int numArea = Integer.parseInt(area);
                int numPeople = Integer.parseInt(people);
                country = new Pais(nombre,area,people,lenguage);
                NombreP.setText("");
                AreaP.setText("");
                PoblacionP.setText("");
                IdiomaP.setText("");
            }else{
                System.out.println("Falta informacio!");
                JOptionPane.showMessageDialog(null, "Error!\n¡Faltan datos por ingresar!");
            }
        }catch(NumberFormatException e){
            System.out.println("Error numérico.");
            JOptionPane.showMessageDialog(null, "Error!\n¡Ingreso un dato numério de forma incorrecta!");
        }
    }//GEN-LAST:event_AgregarPaisActionPerformed

    private void agregarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProvinciaActionPerformed
        // TODO add your handling code here:
        if(country != null){
            String provincia = ProvinciaText.getText();
            country.agregarProvincia(provincia);
            ProvinciaText.setText("");
        }else{
            ProvinciaText.setText("");
            LimiteText.setText("");
            JOptionPane.showMessageDialog(null, "Error!\n¡No hay agregado un país!");
        }
    }//GEN-LAST:event_agregarProvinciaActionPerformed

    private void AgregarPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPaisesActionPerformed
        // TODO add your handling code here:
        if(country != null){
            doc.AgregarPais(country);
            country = null;
        }else{
           JOptionPane.showMessageDialog(null, "Error!\n¡No hay agregado un país!");//showMessageDialog(null,"Error!","¡No hay agregado un país!");
        }
    }//GEN-LAST:event_AgregarPaisesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        doc.Guardar();
        JOptionPane.showMessageDialog(null, "Guardo!\n¡Su documento se ha creado corretamente!");
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarLimite;
    private javax.swing.JButton AgregarPais;
    private javax.swing.JButton AgregarPaises;
    private javax.swing.JTextField AreaP;
    private javax.swing.JTextField IdiomaP;
    private javax.swing.JLabel LabelArea;
    private javax.swing.JLabel LabelLimite;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPoblacion;
    private javax.swing.JLabel LabelProvincia;
    private javax.swing.JTextField LimiteText;
    private javax.swing.JTextField NombreP;
    private javax.swing.JTextField PoblacionP;
    private javax.swing.JTextField ProvinciaText;
    private javax.swing.JButton agregarProvincia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
